name: build
env:
  BUILD_TYPE: Release
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        build_type: [RelWithDebInfo]
        enable_ui: [off]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Install Dependencies
        run: |
          echo "No additional dependencies required for Windows"
      - uses: aseprite/get-ninja@main
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Workaround for windows-2022 and cmake 3.25.0
        shell: bash
        run: rm -rf C:\Strawberry
      - name: Generating Makefiles
        shell: bash
        run: |
          export enable_ccache=off
          cmake -S . -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -DENABLE_TESTS=ON \
            -DENABLE_UI=${{ matrix.enable_ui }} \
            -DENABLE_CCACHE=$enable_ccache
      - name: Compiling
        shell: bash
        run: |
          cd build && ninja
      - name: Make portable zip
        run: |
          echo '# This file is here so Aseprite behaves as a portable program' > build\bin\aseprite.ini
      - name: Create release
        run: |
          7z -tzip a build\Aseprite-${{ steps.version_info.outputs.latest_tag }}-windows.zip build\*

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "major"
          release_name: Release ${{ steps.version_info.outputs.latest_tag }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build\bin\Aseprite-${{ steps.version_info.outputs.latest_tag }}-windows.zip
          asset_name: Aseprite-${{ steps.version_info.outputs.latest_tag }}-windows.zip
          asset_content_type: application/zip
